<script lang="ts">
	import ChartBar from '../components/charts/bar/Index.svelte';
	import ChartStacked from '../components/charts/stacked/Index.svelte';
	import Sprite from '../components/icons/Sprite.svelte';

	const dummyBarData = [
		{ category: 'insurance', value: 2 },
		{ category: 'entertainment', value: 7 },
		{ category: 'something', value: 5 },
	];

	const dummyStackedData = [
		{
			category: 'insurance',
			reminder1: 3840,
			reminder2: 1920,
			reminder3: 960,
			reminder4: 400,
		},
		{
			category: 'entertainment',
			reminder1: 1600,
			reminder2: 1440,
			reminder3: 960,
			reminder4: 400,
		},
		{
			category: 'something',
			reminder1: 820,
			reminder2: 1000,
			reminder3: 640,
			reminder4: 400,
		},
		{
			category: 'else',
			reminder1: 820,
			reminder2: 560,
			reminder3: 720,
			reminder4: 400,
		},
	];
</script>

<h1>Dashboard</h1>

<section>
	<h2>Categories</h2>

	<div>
		<section>
			<h3>Most used</h3>
			<ChartBar data="{dummyBarData}" />
		</section>

		<section>
			<h3>Outgoings</h3>
			<ChartStacked data="{dummyStackedData}" />
		</section>
	</div>
</section>

<section>
	<h2>Upcoming reminders</h2>
	<table>
		<thead>
			<tr>
				<th>Company</th>
				<th>Category</th>
				<th>Due date</th>
				<th>Auto renewal?</th>
				<th>Telephone</th>
				<th>Email</th>
			</tr>
		</thead>
		<tbody>
			<!-- {#each data.reminders as reminders}
				<tr>
					<td>{reminders.reminder.company}</td>
					<td>{reminders.reminder.categoryId}</td>
					<td>{reminders.reminder.dateOfRenewal}</td>
					<td>{reminders.reminder.autoRenewal}</td>
					<td></td>
					<td></td>
				</tr>
			{/each} -->
		</tbody>
	</table>
</section>

<svelte:component this={Sprite} />

<svg class="icon">
	<use xlink:href="#500px"></use>
</svg><svg class="icon">
	<use xlink:href="#add-to-list"></use>
</svg><svg class="icon">
	<use xlink:href="#add-user"></use>
</svg><svg class="icon">
	<use xlink:href="#address"></use>
</svg><svg class="icon">
	<use xlink:href="#adjust"></use>
</svg><svg class="icon">
	<use xlink:href="#air"></use>
</svg><svg class="icon">
	<use xlink:href="#aircraft-landing"></use>
</svg><svg class="icon">
	<use xlink:href="#aircraft-take-off"></use>
</svg><svg class="icon">
	<use xlink:href="#aircraft"></use>
</svg><svg class="icon">
	<use xlink:href="#align-bottom"></use>
</svg><svg class="icon">
	<use xlink:href="#align-horizontal-middle"></use>
</svg><svg class="icon">
	<use xlink:href="#align-left"></use>
</svg><svg class="icon">
	<use xlink:href="#align-right"></use>
</svg><svg class="icon">
	<use xlink:href="#align-top"></use>
</svg><svg class="icon">
	<use xlink:href="#align-vertical-middle"></use>
</svg><svg class="icon">
	<use xlink:href="#archive"></use>
</svg><svg class="icon">
	<use xlink:href="#area-graph"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-bold-down"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-bold-left"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-bold-right"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-bold-up"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-down"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-left"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-long-down"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-long-left"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-long-right"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-long-up"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-right"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-up"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-with-circle-down"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-with-circle-left"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-with-circle-right"></use>
</svg><svg class="icon">
	<use xlink:href="#awareness-ribbon"></use>
</svg><svg class="icon">
	<use xlink:href="#attachment"></use>
</svg><svg class="icon">
	<use xlink:href="#back-in-time"></use>
</svg><svg class="icon">
	<use xlink:href="#arrow-with-circle-up"></use>
</svg><svg class="icon">
	<use xlink:href="#back"></use>
</svg><svg class="icon">
	<use xlink:href="#baidu"></use>
</svg><svg class="icon">
	<use xlink:href="#bar-graph"></use>
</svg><svg class="icon">
	<use xlink:href="#basecamp"></use>
</svg><svg class="icon">
	<use xlink:href="#battery"></use>
</svg><svg class="icon">
	<use xlink:href="#beamed-note"></use>
</svg><svg class="icon">
	<use xlink:href="#bell"></use>
</svg><svg class="icon">
	<use xlink:href="#blackboard"></use>
</svg><svg class="icon">
	<use xlink:href="#block"></use>
</svg><svg class="icon">
	<use xlink:href="#book"></use>
</svg><svg class="icon">
	<use xlink:href="#bookmark"></use>
</svg><svg class="icon">
	<use xlink:href="#bookmarks"></use>
</svg><svg class="icon">
	<use xlink:href="#bowl"></use>
</svg><svg class="icon">
	<use xlink:href="#box"></use>
</svg><svg class="icon">
	<use xlink:href="#briefcase"></use>
</svg><svg class="icon">
	<use xlink:href="#browser"></use>
</svg><svg class="icon">
	<use xlink:href="#bucket"></use>
</svg><svg class="icon">
	<use xlink:href="#brush"></use>
</svg><svg class="icon">
	<use xlink:href="#bug"></use>
</svg><svg class="icon">
	<use xlink:href="#calculator"></use>
</svg><svg class="icon">
	<use xlink:href="#calendar"></use>
</svg><svg class="icon">
	<use xlink:href="#cake"></use>
</svg><svg class="icon">
	<use xlink:href="#camera"></use>
</svg><svg class="icon">
	<use xlink:href="#ccw"></use>
</svg><svg class="icon">
	<use xlink:href="#chat"></use>
</svg><svg class="icon">
	<use xlink:href="#check"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-left"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-down"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-small-down"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-small-left"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-right"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-small-up"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-small-right"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-thin-down"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-thin-left"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-thin-right"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-up"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-thin-up"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-with-circle-down"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-with-circle-left"></use>
</svg><svg class="icon">
	<use xlink:href="#circle-with-cross"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-with-circle-right"></use>
</svg><svg class="icon">
	<use xlink:href="#chevron-with-circle-up"></use>
</svg><svg class="icon">
	<use xlink:href="#circle-with-plus"></use>
</svg><svg class="icon">
	<use xlink:href="#circle-with-minus"></use>
</svg><svg class="icon">
	<use xlink:href="#circle"></use>
</svg><svg class="icon">
	<use xlink:href="#circular-graph"></use>
</svg><svg class="icon">
	<use xlink:href="#classic-computer"></use>
</svg><svg class="icon">
	<use xlink:href="#clapperboard"></use>
</svg><svg class="icon">
	<use xlink:href="#clipboard"></use>
</svg><svg class="icon">
	<use xlink:href="#clock"></use>
</svg><svg class="icon">
	<use xlink:href="#code"></use>
</svg><svg class="icon">
	<use xlink:href="#cloud"></use>
</svg><svg class="icon">
	<use xlink:href="#cog"></use>
</svg><svg class="icon">
	<use xlink:href="#colours"></use>
</svg><svg class="icon">
	<use xlink:href="#compass"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-fast-backward"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-fast-forward"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-next"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-paus"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-jump-to-start"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-play"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-record"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-stop"></use>
</svg><svg class="icon">
	<use xlink:href="#controller-volume"></use>
</svg><svg class="icon">
	<use xlink:href="#copy"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-cloud"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons-attribution"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons-noderivs"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons-noncommercial-us"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons-noncommercial-eu"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons-public-domain"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons-remix"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons-share"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons-sharealike"></use>
</svg><svg class="icon">
	<use xlink:href="#creative-commons"></use>
</svg><svg class="icon">
	<use xlink:href="#credit-card"></use>
</svg><svg class="icon">
	<use xlink:href="#credit"></use>
</svg><svg class="icon">
	<use xlink:href="#crop"></use>
</svg><svg class="icon">
	<use xlink:href="#cup"></use>
</svg><svg class="icon">
	<use xlink:href="#cross"></use>
</svg><svg class="icon">
	<use xlink:href="#cw"></use>
</svg><svg class="icon">
	<use xlink:href="#database"></use>
</svg><svg class="icon">
	<use xlink:href="#cycle"></use>
</svg><svg class="icon">
	<use xlink:href="#direction"></use>
</svg><svg class="icon">
	<use xlink:href="#document-landscape"></use>
</svg><svg class="icon">
	<use xlink:href="#dial-pad"></use>
</svg><svg class="icon">
	<use xlink:href="#document"></use>
</svg><svg class="icon">
	<use xlink:href="#documents"></use>
</svg><svg class="icon">
	<use xlink:href="#dot-single"></use>
</svg><svg class="icon">
	<use xlink:href="#dots-three-horizontal"></use>
</svg><svg class="icon">
	<use xlink:href="#dots-three-vertical"></use>
</svg><svg class="icon">
	<use xlink:href="#dots-two-vertical"></use>
</svg><svg class="icon">
	<use xlink:href="#dots-two-horizontal"></use>
</svg><svg class="icon">
	<use xlink:href="#download"></use>
</svg><svg class="icon">
	<use xlink:href="#drive"></use>
</svg><svg class="icon">
	<use xlink:href="#drink"></use>
</svg><svg class="icon">
	<use xlink:href="#drop"></use>
</svg><svg class="icon">
	<use xlink:href="#dropbox"></use>
</svg><svg class="icon">
	<use xlink:href="#edit"></use>
</svg><svg class="icon">
	<use xlink:href="#email"></use>
</svg><svg class="icon">
	<use xlink:href="#emoji-flirt"></use>
</svg><svg class="icon">
	<use xlink:href="#emoji-neutral"></use>
</svg><svg class="icon">
	<use xlink:href="#emoji-happy"></use>
</svg><svg class="icon">
	<use xlink:href="#emoji-sad"></use>
</svg><svg class="icon">
	<use xlink:href="#eraser"></use>
</svg><svg class="icon">
	<use xlink:href="#erase"></use>
</svg><svg class="icon">
	<use xlink:href="#eye-with-line"></use>
</svg><svg class="icon">
	<use xlink:href="#eye"></use>
</svg><svg class="icon">
	<use xlink:href="#export"></use>
</svg><svg class="icon">
	<use xlink:href="#feather"></use>
</svg><svg class="icon">
	<use xlink:href="#fingerprint"></use>
</svg><svg class="icon">
	<use xlink:href="#flash"></use>
</svg><svg class="icon">
	<use xlink:href="#flag"></use>
</svg><svg class="icon">
	<use xlink:href="#flashlight"></use>
</svg><svg class="icon">
	<use xlink:href="#flat-brush"></use>
</svg><svg class="icon">
	<use xlink:href="#flow-cascade"></use>
</svg><svg class="icon">
	<use xlink:href="#flow-branch"></use>
</svg><svg class="icon">
	<use xlink:href="#flattr"></use>
</svg><svg class="icon">
	<use xlink:href="#flow-parallel"></use>
</svg><svg class="icon">
	<use xlink:href="#flow-line"></use>
</svg><svg class="icon">
	<use xlink:href="#flower"></use>
</svg><svg class="icon">
	<use xlink:href="#folder-images"></use>
</svg><svg class="icon">
	<use xlink:href="#flow-tree"></use>
</svg><svg class="icon">
	<use xlink:href="#folder-music"></use>
</svg><svg class="icon">
	<use xlink:href="#folder-video"></use>
</svg><svg class="icon">
	<use xlink:href="#funnel"></use>
</svg><svg class="icon">
	<use xlink:href="#folder"></use>
</svg><svg class="icon">
	<use xlink:href="#forward"></use>
</svg><svg class="icon">
	<use xlink:href="#game-controller"></use>
</svg><svg class="icon">
	<use xlink:href="#gauge"></use>
</svg><svg class="icon">
	<use xlink:href="#graduation-cap"></use>
</svg><svg class="icon">
	<use xlink:href="#globe"></use>
</svg><svg class="icon">
	<use xlink:href="#grid"></use>
</svg><svg class="icon">
	<use xlink:href="#hand"></use>
</svg><svg class="icon">
	<use xlink:href="#hair-cross"></use>
</svg><svg class="icon">
	<use xlink:href="#heart-outlined"></use>
</svg><svg class="icon">
	<use xlink:href="#help-with-circle"></use>
</svg><svg class="icon">
	<use xlink:href="#heart"></use>
</svg><svg class="icon">
	<use xlink:href="#home"></use>
</svg><svg class="icon">
	<use xlink:href="#hour-glass"></use>
</svg><svg class="icon">
	<use xlink:href="#help"></use>
</svg><svg class="icon">
	<use xlink:href="#houzz"></use>
</svg><svg class="icon">
	<use xlink:href="#icloud"></use>
</svg><svg class="icon">
	<use xlink:href="#image"></use>
</svg><svg class="icon">
	<use xlink:href="#image-inverted"></use>
</svg><svg class="icon">
	<use xlink:href="#images"></use>
</svg><svg class="icon">
	<use xlink:href="#inbox"></use>
</svg><svg class="icon">
	<use xlink:href="#infinity"></use>
</svg><svg class="icon">
	<use xlink:href="#info"></use>
</svg><svg class="icon">
	<use xlink:href="#install"></use>
</svg><svg class="icon">
	<use xlink:href="#keyboard"></use>
</svg><svg class="icon">
	<use xlink:href="#key"></use>
</svg><svg class="icon">
	<use xlink:href="#lab-flask"></use>
</svg><svg class="icon">
	<use xlink:href="#landline"></use>
</svg><svg class="icon">
	<use xlink:href="#language"></use>
</svg><svg class="icon">
	<use xlink:href="#laptop"></use>
</svg><svg class="icon">
	<use xlink:href="#layers"></use>
</svg><svg class="icon">
	<use xlink:href="#leaf"></use>
</svg><svg class="icon">
	<use xlink:href="#level-down"></use>
</svg><svg class="icon">
	<use xlink:href="#level-up"></use>
</svg><svg class="icon">
	<use xlink:href="#lifebuoy"></use>
</svg><svg class="icon">
	<use xlink:href="#light-down"></use>
</svg><svg class="icon">
	<use xlink:href="#light-bulb"></use>
</svg><svg class="icon">
	<use xlink:href="#light-up"></use>
</svg><svg class="icon">
	<use xlink:href="#line-graph"></use>
</svg><svg class="icon">
	<use xlink:href="#link"></use>
</svg><svg class="icon">
	<use xlink:href="#list"></use>
</svg><svg class="icon">
	<use xlink:href="#location-pin"></use>
</svg><svg class="icon">
	<use xlink:href="#lock-open"></use>
</svg><svg class="icon">
	<use xlink:href="#location"></use>
</svg><svg class="icon">
	<use xlink:href="#lock"></use>
</svg><svg class="icon">
	<use xlink:href="#log-out"></use>
</svg><svg class="icon">
	<use xlink:href="#login"></use>
</svg><svg class="icon">
	<use xlink:href="#loop"></use>
</svg><svg class="icon">
	<use xlink:href="#magnet"></use>
</svg><svg class="icon">
	<use xlink:href="#magnifying-glass"></use>
</svg><svg class="icon">
	<use xlink:href="#mail"></use>
</svg><svg class="icon">
	<use xlink:href="#man"></use>
</svg><svg class="icon">
	<use xlink:href="#map"></use>
</svg><svg class="icon">
	<use xlink:href="#mask"></use>
</svg><svg class="icon">
	<use xlink:href="#medal"></use>
</svg><svg class="icon">
	<use xlink:href="#megaphone"></use>
</svg><svg class="icon">
	<use xlink:href="#merge"></use>
</svg><svg class="icon">
	<use xlink:href="#menu"></use>
</svg><svg class="icon">
	<use xlink:href="#mic"></use>
</svg><svg class="icon">
	<use xlink:href="#message"></use>
</svg><svg class="icon">
	<use xlink:href="#minus"></use>
</svg><svg class="icon">
	<use xlink:href="#mobile"></use>
</svg><svg class="icon">
	<use xlink:href="#modern-mic"></use>
</svg><svg class="icon">
	<use xlink:href="#moon"></use>
</svg><svg class="icon">
	<use xlink:href="#mouse-pointer"></use>
</svg><svg class="icon">
	<use xlink:href="#mouse"></use>
</svg><svg class="icon">
	<use xlink:href="#music"></use>
</svg><svg class="icon">
	<use xlink:href="#network"></use>
</svg><svg class="icon">
	<use xlink:href="#new-message"></use>
</svg><svg class="icon">
	<use xlink:href="#new"></use>
</svg><svg class="icon">
	<use xlink:href="#newsletter"></use>
</svg><svg class="icon">
	<use xlink:href="#news"></use>
</svg><svg class="icon">
	<use xlink:href="#note"></use>
</svg><svg class="icon">
	<use xlink:href="#notifications-off"></use>
</svg><svg class="icon">
	<use xlink:href="#notification"></use>
</svg><svg class="icon">
	<use xlink:href="#old-mobile"></use>
</svg><svg class="icon">
	<use xlink:href="#onedrive"></use>
</svg><svg class="icon">
	<use xlink:href="#old-phone"></use>
</svg><svg class="icon">
	<use xlink:href="#palette"></use>
</svg><svg class="icon">
	<use xlink:href="#open-book"></use>
</svg><svg class="icon">
	<use xlink:href="#paypal"></use>
</svg><svg class="icon">
	<use xlink:href="#picasa"></use>
</svg><svg class="icon">
	<use xlink:href="#paper-plane"></use>
</svg><svg class="icon">
	<use xlink:href="#pencil"></use>
</svg><svg class="icon">
	<use xlink:href="#phone"></use>
</svg><svg class="icon">
	<use xlink:href="#pin"></use>
</svg><svg class="icon">
	<use xlink:href="#popup"></use>
</svg><svg class="icon">
	<use xlink:href="#plus"></use>
</svg><svg class="icon">
	<use xlink:href="#power-plug"></use>
</svg><svg class="icon">
	<use xlink:href="#pie-chart"></use>
</svg><svg class="icon">
	<use xlink:href="#price-tag"></use>
</svg><svg class="icon">
	<use xlink:href="#price-ribbon"></use>
</svg><svg class="icon">
	<use xlink:href="#print"></use>
</svg><svg class="icon">
	<use xlink:href="#progress-empty"></use>
</svg><svg class="icon">
	<use xlink:href="#progress-full"></use>
</svg><svg class="icon">
	<use xlink:href="#progress-one"></use>
</svg><svg class="icon">
	<use xlink:href="#progress-two"></use>
</svg><svg class="icon">
	<use xlink:href="#radio"></use>
</svg><svg class="icon">
	<use xlink:href="#quote"></use>
</svg><svg class="icon">
	<use xlink:href="#rainbow"></use>
</svg><svg class="icon">
	<use xlink:href="#publish"></use>
</svg><svg class="icon">
	<use xlink:href="#rdio-with-circle"></use>
</svg><svg class="icon">
	<use xlink:href="#reply-all"></use>
</svg><svg class="icon">
	<use xlink:href="#rdio"></use>
</svg><svg class="icon">
	<use xlink:href="#remove-user"></use>
</svg><svg class="icon">
	<use xlink:href="#reply"></use>
</svg><svg class="icon">
	<use xlink:href="#resize-100"></use>
</svg><svg class="icon">
	<use xlink:href="#resize-full-screen"></use>
</svg><svg class="icon">
	<use xlink:href="#rocket"></use>
</svg><svg class="icon">
	<use xlink:href="#retweet"></use>
</svg><svg class="icon">
	<use xlink:href="#round-brush"></use>
</svg><svg class="icon">
	<use xlink:href="#rss"></use>
</svg><svg class="icon">
	<use xlink:href="#ruler"></use>
</svg><svg class="icon">
	<use xlink:href="#select-arrows"></use>
</svg><svg class="icon">
	<use xlink:href="#save"></use>
</svg><svg class="icon">
	<use xlink:href="#share-alternative"></use>
</svg><svg class="icon">
	<use xlink:href="#share"></use>
</svg><svg class="icon">
	<use xlink:href="#scissors"></use>
</svg><svg class="icon">
	<use xlink:href="#shareable"></use>
</svg><svg class="icon">
	<use xlink:href="#shop"></use>
</svg><svg class="icon">
	<use xlink:href="#shopping-basket"></use>
</svg><svg class="icon">
	<use xlink:href="#shopping-bag"></use>
</svg><svg class="icon">
	<use xlink:href="#shopping-cart"></use>
</svg><svg class="icon">
	<use xlink:href="#shuffle"></use>
</svg><svg class="icon">
	<use xlink:href="#shield"></use>
</svg><svg class="icon">
	<use xlink:href="#sound-mix"></use>
</svg><svg class="icon">
	<use xlink:href="#signal"></use>
</svg><svg class="icon">
	<use xlink:href="#sound-mute"></use>
</svg><svg class="icon">
	<use xlink:href="#sound"></use>
</svg><svg class="icon">
	<use xlink:href="#sports-club"></use>
</svg><svg class="icon">
	<use xlink:href="#spreadsheet"></use>
</svg><svg class="icon">
	<use xlink:href="#squared-cross"></use>
</svg><svg class="icon">
	<use xlink:href="#squared-minus"></use>
</svg><svg class="icon">
	<use xlink:href="#star-outlined"></use>
</svg><svg class="icon">
	<use xlink:href="#squared-plus"></use>
</svg><svg class="icon">
	<use xlink:href="#star"></use>
</svg><svg class="icon">
	<use xlink:href="#stopwatch"></use>
</svg><svg class="icon">
	<use xlink:href="#sweden"></use>
</svg><svg class="icon">
	<use xlink:href="#swap"></use>
</svg><svg class="icon">
	<use xlink:href="#suitcase"></use>
</svg><svg class="icon">
	<use xlink:href="#tablet-mobile-combo"></use>
</svg><svg class="icon">
	<use xlink:href="#switch"></use>
</svg><svg class="icon">
	<use xlink:href="#tablet"></use>
</svg><svg class="icon">
	<use xlink:href="#tag"></use>
</svg><svg class="icon">
	<use xlink:href="#text-document-inverted"></use>
</svg><svg class="icon">
	<use xlink:href="#text-document"></use>
</svg><svg class="icon">
	<use xlink:href="#ticket"></use>
</svg><svg class="icon">
	<use xlink:href="#thermometer"></use>
</svg><svg class="icon">
	<use xlink:href="#thumbs-up"></use>
</svg><svg class="icon">
	<use xlink:href="#thumbs-down"></use>
</svg><svg class="icon">
	<use xlink:href="#tools"></use>
</svg><svg class="icon">
	<use xlink:href="#text"></use>
</svg><svg class="icon">
	<use xlink:href="#thunder-cloud"></use>
</svg><svg class="icon">
	<use xlink:href="#time-slot"></use>
</svg><svg class="icon">
	<use xlink:href="#traffic-cone"></use>
</svg><svg class="icon">
	<use xlink:href="#tree"></use>
</svg><svg class="icon">
	<use xlink:href="#trash"></use>
</svg><svg class="icon">
	<use xlink:href="#triangle-right"></use>
</svg><svg class="icon">
	<use xlink:href="#triangle-left"></use>
</svg><svg class="icon">
	<use xlink:href="#triangle-down"></use>
</svg><svg class="icon">
	<use xlink:href="#tv"></use>
</svg><svg class="icon">
	<use xlink:href="#uninstall"></use>
</svg><svg class="icon">
	<use xlink:href="#unread"></use>
</svg><svg class="icon">
	<use xlink:href="#triangle-up"></use>
</svg><svg class="icon">
	<use xlink:href="#typing"></use>
</svg><svg class="icon">
	<use xlink:href="#trophy"></use>
</svg><svg class="icon">
	<use xlink:href="#users"></use>
</svg><svg class="icon">
	<use xlink:href="#untag"></use>
</svg><svg class="icon">
	<use xlink:href="#upload-to-cloud"></use>
</svg><svg class="icon">
	<use xlink:href="#upload"></use>
</svg><svg class="icon">
	<use xlink:href="#user"></use>
</svg><svg class="icon">
	<use xlink:href="#v-card"></use>
</svg><svg class="icon">
	<use xlink:href="#video"></use>
</svg><svg class="icon">
	<use xlink:href="#vinyl"></use>
</svg><svg class="icon">
	<use xlink:href="#video-camera"></use>
</svg><svg class="icon">
	<use xlink:href="#voicemail"></use>
</svg><svg class="icon">
	<use xlink:href="#warning"></use>
</svg><svg class="icon">
	<use xlink:href="#wallet"></use>
</svg><svg class="icon">
	<use xlink:href="#water"></use>
</svg>

<style>
	div {
		display: grid;
		padding-left: 4rem;
		padding-right: 4rem;
		grid-template-columns: 1fr 1fr;
		grid-gap: 5rem;
	}
</style>
