query getAllReminders(
	$today: Date
	$upcoming: Date
	$first: Int
	$last: Int
	$after: Cursor
	$before: Cursor
) {
	upcoming: remindersCollection(
		filter: { date: { gte: $today, lte: $upcoming } }
	) {
		list: edges {
			reminder: node {
				id
				name
				company
				cost
				date
				autoRenewal
				category {
					iconId
					name
				}
			}
		}
	}
	reminders: remindersCollection(
		first: $first
		last: $last
		after: $after
		before: $before
	) {
		pageInfo {
			startCursor
			endCursor
			hasPreviousPage
			hasNextPage
		}
		list: edges {
			reminder: node {
				id
				name
				company
				cost
				total
				category {
					iconId
					name
				}
			}
		}
	}
}
