query GetReminders(
	$categoryId: BigInt
	$first: Int
	$last: Int
	$after: Cursor
	$before: Cursor
) {
	upcoming: reminderCollection(
		filter: {
			category_id: { eq: $categoryId }
		}
	) {
		list: edges {
			reminder: node {
				id
				name
				company
				cost
				day
				month
				auto_renewal
				category {
					id
					icon_id
					name
				}
			}
		}
	}
	reminders: reminderCollection(
		first: $first
		last: $last
		after: $after
		before: $before
		filter: { category_id: { eq: $categoryId } }
	) {
		pageInfo {
			startCursor
			endCursor
			hasPreviousPage
			hasNextPage
		}
		list: edges {
			reminder: node {
				id
				name
				company
				cost
				category {
					id
					icon_id
					name
				}
			}
		}
	}
}
