query getReminders(
	$categoryId: BigInt
	$today: Date
	$upcoming: Date
	$first: Int
	$last: Int
	$after: Cursor
	$before: Cursor
) {
	upcoming: remindersCollection(
		filter: {
			date: { gte: $today, lte: $upcoming }
			categoryId: { eq: $categoryId }
		}
	) {
		list: edges {
			reminder: node {
				id
				name
				company
				cost
				date
				autoRenewal
				category {
					id
					iconId
					name
				}
			}
		}
	}
	reminders: remindersCollection(
		first: $first
		last: $last
		after: $after
		before: $before
		filter: { categoryId: { eq: $categoryId } }
	) {
		pageInfo {
			startCursor
			endCursor
			hasPreviousPage
			hasNextPage
		}
		list: edges {
			reminder: node {
				id
				name
				company
				cost
				total
				category {
					id
					iconId
					name
				}
			}
		}
	}
}
