mutation addReminder(
	$userId: UUID!
	$categoryId: BigInt!
	$name: String!
	$type: Type!
	$company: String
	$cost: Float
	$date: Date
	$frequency: Frequency
	$autoRenewal: Boolean
	$notes: String
) {
	insertIntoremindersCollection(
		objects: [
			{
				userid: $userId
				categoryId: $categoryId
				name: $name
				type: $type
				company: $company
				cost: $cost
				date: $date
				frequency: $frequency
				autoRenewal: $autoRenewal
				notes: $notes
			}
		]
	) {
		affectedCount
		records {
			id
		}
	}
}
