mutation AddReminder(
	$userId: UUID!
	$categoryId: UUID!
	$name: String!
	$type: Type!
	$cost: Float
	$day: Int
	$month: Int
	$frequency: Frequency
	$autoRenewal: Boolean
	$notes: String
	$startedAt: Date
) {
	insertIntoReminderCollection(
		objects: [
			{
				user_id: $userId
				category_id: $categoryId
				name: $name
				type: $type
				cost: $cost
				day: $day
				month: $month
				frequency: $frequency
				auto_renewal: $autoRenewal
				notes: $notes
				started_at: $startedAt
			}
		]
	) {
		affectedCount
		records {
			id
		}
	}
}
