"""A high precision floating point value represented as a string"""
scalar BigFloat

"""
Boolean expression comparing fields on type "BigFloat"
"""
input BigFloatFilter {
  eq: BigFloat
  gt: BigFloat
  gte: BigFloat
  in: [BigFloat!]
  is: FilterIs
  lt: BigFloat
  lte: BigFloat
  neq: BigFloat
}

"""An arbitrary size integer represented as a string"""
scalar BigInt

"""
Boolean expression comparing fields on type "BigInt"
"""
input BigIntFilter {
  eq: BigInt
  gt: BigInt
  gte: BigInt
  in: [BigInt!]
  is: FilterIs
  lt: BigInt
  lte: BigInt
  neq: BigInt
}

"""
Boolean expression comparing fields on type "Boolean"
"""
input BooleanFilter {
  eq: Boolean
  is: FilterIs
}

type Category implements Node {
  created_at: Datetime
  icon_id: String
  id: UUID!
  name: String!

  """Globally Unique Record Identifier"""
  nodeId: ID!
  reminderCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Filters to apply to the results set when querying from the collection"""
    filter: ReminderFilter

    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Sort order to apply to the collection"""
    orderBy: [ReminderOrderBy!]
  ): ReminderConnection
  settings: Settings
  user_id: UUID
}

type CategoryConnection {
  edges: [CategoryEdge!]!
  pageInfo: PageInfo!
}

type CategoryDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Category!]!
}

type CategoryEdge {
  cursor: String!
  node: Category!
}

input CategoryFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [CategoryFilter!]
  created_at: DatetimeFilter
  icon_id: StringFilter
  id: UUIDFilter
  name: StringFilter
  nodeId: IDFilter

  """Negates a filter"""
  not: CategoryFilter

  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [CategoryFilter!]
  user_id: UUIDFilter
}

input CategoryInsertInput {
  created_at: Datetime
  icon_id: String
  id: UUID
  name: String
  user_id: UUID
}

type CategoryInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Category!]!
}

input CategoryOrderBy {
  created_at: OrderByDirection
  icon_id: OrderByDirection
  id: OrderByDirection
  name: OrderByDirection
  user_id: OrderByDirection
}

input CategoryUpdateInput {
  created_at: Datetime
  icon_id: String
  id: UUID
  name: String
  user_id: UUID
}

type CategoryUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Category!]!
}

enum Currency {
  AUD
  CAD
  EUR
  GBP
  JPY
  USD
}

"""
Boolean expression comparing fields on type "Currency"
"""
input CurrencyFilter {
  eq: Currency
  in: [Currency!]
  is: FilterIs
  neq: Currency
}

"""
An opaque string using for tracking a position in results during pagination
"""
scalar Cursor

"""A date wihout time information"""
scalar Date

"""
Boolean expression comparing fields on type "Date"
"""
input DateFilter {
  eq: Date
  gt: Date
  gte: Date
  in: [Date!]
  is: FilterIs
  lt: Date
  lte: Date
  neq: Date
}

"""A date and time"""
scalar Datetime

"""
Boolean expression comparing fields on type "Datetime"
"""
input DatetimeFilter {
  eq: Datetime
  gt: Datetime
  gte: Datetime
  in: [Datetime!]
  is: FilterIs
  lt: Datetime
  lte: Datetime
  neq: Datetime
}

enum FilterIs {
  NOT_NULL
  NULL
}

"""
Boolean expression comparing fields on type "Float"
"""
input FloatFilter {
  eq: Float
  gt: Float
  gte: Float
  in: [Float!]
  is: FilterIs
  lt: Float
  lte: Float
  neq: Float
}

enum Frequency {
  ANNUAL
  MONTHLY
}

"""
Boolean expression comparing fields on type "Frequency"
"""
input FrequencyFilter {
  eq: Frequency
  in: [Frequency!]
  is: FilterIs
  neq: Frequency
}

type History implements Node {
  auto_renewal: Boolean!
  category_id: UUID
  cost: Float!
  created_at: Datetime
  day: Int
  frequency: Frequency
  id: UUID!
  month: Int

  """Globally Unique Record Identifier"""
  nodeId: ID!
  operation_type: OperationType
  reminder_id: UUID
  settings: Settings
  started_at: Date
  type: Type!
  user_id: UUID
}

type HistoryConnection {
  edges: [HistoryEdge!]!
  pageInfo: PageInfo!
}

type HistoryDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [History!]!
}

type HistoryEdge {
  cursor: String!
  node: History!
}

input HistoryFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [HistoryFilter!]
  auto_renewal: BooleanFilter
  category_id: UUIDFilter
  cost: FloatFilter
  created_at: DatetimeFilter
  day: IntFilter
  frequency: FrequencyFilter
  id: UUIDFilter
  month: IntFilter
  nodeId: IDFilter

  """Negates a filter"""
  not: HistoryFilter
  operation_type: OperationTypeFilter

  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [HistoryFilter!]
  reminder_id: UUIDFilter
  started_at: DateFilter
  type: TypeFilter
  user_id: UUIDFilter
}

input HistoryInsertInput {
  auto_renewal: Boolean
  category_id: UUID
  cost: Float
  created_at: Datetime
  day: Int
  frequency: Frequency
  id: UUID
  month: Int
  operation_type: OperationType
  reminder_id: UUID
  started_at: Date
  type: Type
  user_id: UUID
}

type HistoryInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [History!]!
}

input HistoryOrderBy {
  auto_renewal: OrderByDirection
  category_id: OrderByDirection
  cost: OrderByDirection
  created_at: OrderByDirection
  day: OrderByDirection
  frequency: OrderByDirection
  id: OrderByDirection
  month: OrderByDirection
  operation_type: OrderByDirection
  reminder_id: OrderByDirection
  started_at: OrderByDirection
  type: OrderByDirection
  user_id: OrderByDirection
}

input HistoryUpdateInput {
  auto_renewal: Boolean
  category_id: UUID
  cost: Float
  created_at: Datetime
  day: Int
  frequency: Frequency
  id: UUID
  month: Int
  operation_type: OperationType
  reminder_id: UUID
  started_at: Date
  type: Type
  user_id: UUID
}

type HistoryUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [History!]!
}

"""
Boolean expression comparing fields on type "ID"
"""
input IDFilter {
  eq: ID
}

"""
Boolean expression comparing fields on type "Int"
"""
input IntFilter {
  eq: Int
  gt: Int
  gte: Int
  in: [Int!]
  is: FilterIs
  lt: Int
  lte: Int
  neq: Int
}

enum Interval {
  DAYS
  MONTHS
  YEARS
}

"""
Boolean expression comparing fields on type "Interval"
"""
input IntervalFilter {
  eq: Interval
  in: [Interval!]
  is: FilterIs
  neq: Interval
}

"""A Javascript Object Notation value serialized as a string"""
scalar JSON

"""The root type for creating and mutating data"""
type Mutation {
  """Deletes zero or more records from the `Category` collection"""
  deleteFromCategoryCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1

    """Restricts the mutation's impact to records matching the criteria"""
    filter: CategoryFilter
  ): CategoryDeleteResponse!

  """Deletes zero or more records from the `History` collection"""
  deleteFromHistoryCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1

    """Restricts the mutation's impact to records matching the criteria"""
    filter: HistoryFilter
  ): HistoryDeleteResponse!

  """Deletes zero or more records from the `Reminder` collection"""
  deleteFromReminderCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1

    """Restricts the mutation's impact to records matching the criteria"""
    filter: ReminderFilter
  ): ReminderDeleteResponse!

  """Deletes zero or more records from the `Settings` collection"""
  deleteFromSettingsCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1

    """Restricts the mutation's impact to records matching the criteria"""
    filter: SettingsFilter
  ): SettingsDeleteResponse!

  """Adds one or more `Category` records to the collection"""
  insertIntoCategoryCollection(objects: [CategoryInsertInput!]!): CategoryInsertResponse

  """Adds one or more `History` records to the collection"""
  insertIntoHistoryCollection(objects: [HistoryInsertInput!]!): HistoryInsertResponse

  """Adds one or more `Reminder` records to the collection"""
  insertIntoReminderCollection(objects: [ReminderInsertInput!]!): ReminderInsertResponse

  """Adds one or more `Settings` records to the collection"""
  insertIntoSettingsCollection(objects: [SettingsInsertInput!]!): SettingsInsertResponse

  """Updates zero or more records in the `Category` collection"""
  updateCategoryCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1

    """Restricts the mutation's impact to records matching the criteria"""
    filter: CategoryFilter

    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: CategoryUpdateInput!
  ): CategoryUpdateResponse!

  """Updates zero or more records in the `History` collection"""
  updateHistoryCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1

    """Restricts the mutation's impact to records matching the criteria"""
    filter: HistoryFilter

    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: HistoryUpdateInput!
  ): HistoryUpdateResponse!

  """Updates zero or more records in the `Reminder` collection"""
  updateReminderCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1

    """Restricts the mutation's impact to records matching the criteria"""
    filter: ReminderFilter

    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: ReminderUpdateInput!
  ): ReminderUpdateResponse!

  """Updates zero or more records in the `Settings` collection"""
  updateSettingsCollection(
    """
    The maximum number of records in the collection permitted to be affected
    """
    atMost: Int! = 1

    """Restricts the mutation's impact to records matching the criteria"""
    filter: SettingsFilter

    """
    Fields that are set will be updated for all records matching the `filter`
    """
    set: SettingsUpdateInput!
  ): SettingsUpdateResponse!
}

interface Node {
  """Retrieves a record by `ID`"""
  nodeId: ID!
}

"""Any type not handled by the type system"""
scalar Opaque

"""
Boolean expression comparing fields on type "Opaque"
"""
input OpaqueFilter {
  eq: Opaque
  is: FilterIs
}

enum OperationType {
  ReminderCreated
  ReminderDeleted
  ReminderUpdated
}

"""
Boolean expression comparing fields on type "OperationType"
"""
input OperationTypeFilter {
  eq: OperationType
  in: [OperationType!]
  is: FilterIs
  neq: OperationType
}

"""Defines a per-field sorting order"""
enum OrderByDirection {
  """Ascending order, nulls first"""
  AscNullsFirst

  """Ascending order, nulls last"""
  AscNullsLast

  """Descending order, nulls first"""
  DescNullsFirst

  """Descending order, nulls last"""
  DescNullsLast
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

"""The root type for querying data"""
type Query {
  """A pagable collection of type `Category`"""
  categoryCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Filters to apply to the results set when querying from the collection"""
    filter: CategoryFilter

    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Sort order to apply to the collection"""
    orderBy: [CategoryOrderBy!]
  ): CategoryConnection

  """A pagable collection of type `History`"""
  historyCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Filters to apply to the results set when querying from the collection"""
    filter: HistoryFilter

    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Sort order to apply to the collection"""
    orderBy: [HistoryOrderBy!]
  ): HistoryConnection

  """Retrieve a record by its `ID`"""
  node(
    """The record's `ID`"""
    nodeId: ID!
  ): Node

  """A pagable collection of type `Reminder`"""
  reminderCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Filters to apply to the results set when querying from the collection"""
    filter: ReminderFilter

    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Sort order to apply to the collection"""
    orderBy: [ReminderOrderBy!]
  ): ReminderConnection

  """A pagable collection of type `Settings`"""
  settingsCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Filters to apply to the results set when querying from the collection"""
    filter: SettingsFilter

    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Sort order to apply to the collection"""
    orderBy: [SettingsOrderBy!]
  ): SettingsConnection
}

type Reminder implements Node {
  auto_renewal: Boolean!
  category: Category
  category_id: UUID
  company: String!
  cost: Float!
  created_at: Datetime
  day: Int
  frequency: Frequency
  id: UUID!
  month: Int
  name: String!

  """Globally Unique Record Identifier"""
  nodeId: ID!
  notes: String
  settings: Settings
  started_at: Date
  type: Type!
  user_id: UUID
}

type ReminderConnection {
  edges: [ReminderEdge!]!
  pageInfo: PageInfo!

  """The total number of records matching the `filter` criteria"""
  totalCount: Int!
}

type ReminderDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Reminder!]!
}

type ReminderEdge {
  cursor: String!
  node: Reminder!
}

input ReminderFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [ReminderFilter!]
  auto_renewal: BooleanFilter
  category_id: UUIDFilter
  company: StringFilter
  cost: FloatFilter
  created_at: DatetimeFilter
  day: IntFilter
  frequency: FrequencyFilter
  id: UUIDFilter
  month: IntFilter
  name: StringFilter
  nodeId: IDFilter

  """Negates a filter"""
  not: ReminderFilter
  notes: StringFilter

  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [ReminderFilter!]
  started_at: DateFilter
  type: TypeFilter
  user_id: UUIDFilter
}

input ReminderInsertInput {
  auto_renewal: Boolean
  category_id: UUID
  company: String
  cost: Float
  created_at: Datetime
  day: Int
  frequency: Frequency
  id: UUID
  month: Int
  name: String
  notes: String
  started_at: Date
  type: Type
  user_id: UUID
}

type ReminderInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Reminder!]!
}

input ReminderOrderBy {
  auto_renewal: OrderByDirection
  category_id: OrderByDirection
  company: OrderByDirection
  cost: OrderByDirection
  created_at: OrderByDirection
  day: OrderByDirection
  frequency: OrderByDirection
  id: OrderByDirection
  month: OrderByDirection
  name: OrderByDirection
  notes: OrderByDirection
  started_at: OrderByDirection
  type: OrderByDirection
  user_id: OrderByDirection
}

input ReminderUpdateInput {
  auto_renewal: Boolean
  category_id: UUID
  company: String
  cost: Float
  created_at: Datetime
  day: Int
  frequency: Frequency
  id: UUID
  month: Int
  name: String
  notes: String
  started_at: Date
  type: Type
  user_id: UUID
}

type ReminderUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Reminder!]!
}

type Settings implements Node {
  categoryCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Filters to apply to the results set when querying from the collection"""
    filter: CategoryFilter

    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Sort order to apply to the collection"""
    orderBy: [CategoryOrderBy!]
  ): CategoryConnection
  currency: Currency
  email: String
  first_name: String
  historyCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Filters to apply to the results set when querying from the collection"""
    filter: HistoryFilter

    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Sort order to apply to the collection"""
    orderBy: [HistoryOrderBy!]
  ): HistoryConnection
  id: UUID!
  interval: Interval
  last_name: String

  """Globally Unique Record Identifier"""
  nodeId: ID!
  notice_period: Int
  reminderCollection(
    """Query values in the collection after the provided cursor"""
    after: Cursor

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Filters to apply to the results set when querying from the collection"""
    filter: ReminderFilter

    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Sort order to apply to the collection"""
    orderBy: [ReminderOrderBy!]
  ): ReminderConnection
  updated_at: Datetime
}

type SettingsConnection {
  edges: [SettingsEdge!]!
  pageInfo: PageInfo!
}

type SettingsDeleteResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Settings!]!
}

type SettingsEdge {
  cursor: String!
  node: Settings!
}

input SettingsFilter {
  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [SettingsFilter!]
  currency: CurrencyFilter
  email: StringFilter
  first_name: StringFilter
  id: UUIDFilter
  interval: IntervalFilter
  last_name: StringFilter
  nodeId: IDFilter

  """Negates a filter"""
  not: SettingsFilter
  notice_period: IntFilter

  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [SettingsFilter!]
  updated_at: DatetimeFilter
}

input SettingsInsertInput {
  currency: Currency
  email: String
  first_name: String
  id: UUID
  interval: Interval
  last_name: String
  notice_period: Int
  updated_at: Datetime
}

type SettingsInsertResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Settings!]!
}

input SettingsOrderBy {
  currency: OrderByDirection
  email: OrderByDirection
  first_name: OrderByDirection
  id: OrderByDirection
  interval: OrderByDirection
  last_name: OrderByDirection
  notice_period: OrderByDirection
  updated_at: OrderByDirection
}

input SettingsUpdateInput {
  currency: Currency
  email: String
  first_name: String
  id: UUID
  interval: Interval
  last_name: String
  notice_period: Int
  updated_at: Datetime
}

type SettingsUpdateResponse {
  """Count of the records impacted by the mutation"""
  affectedCount: Int!

  """Array of records impacted by the mutation"""
  records: [Settings!]!
}

"""
Boolean expression comparing fields on type "String"
"""
input StringFilter {
  eq: String
  gt: String
  gte: String
  ilike: String
  in: [String!]
  iregex: String
  is: FilterIs
  like: String
  lt: String
  lte: String
  neq: String
  regex: String
  startsWith: String
}

"""A time without date information"""
scalar Time

"""
Boolean expression comparing fields on type "Time"
"""
input TimeFilter {
  eq: Time
  gt: Time
  gte: Time
  in: [Time!]
  is: FilterIs
  lt: Time
  lte: Time
  neq: Time
}

enum Type {
  ONGOING
  SINGLE
}

"""
Boolean expression comparing fields on type "Type"
"""
input TypeFilter {
  eq: Type
  in: [Type!]
  is: FilterIs
  neq: Type
}

"""A universally unique identifier"""
scalar UUID

"""
Boolean expression comparing fields on type "UUID"
"""
input UUIDFilter {
  eq: UUID
  in: [UUID!]
  is: FilterIs
  neq: UUID
}
