name: Deploy apps services

on:
  pull_request:
    branches: main
    paths:
      - 'terraform/apps/**'
      - 'apps/app/src/lambdas/**'
      - 'apps/app/package.json'
      - 'package.json'
      - '.github/**'
      - '!.github/workflows/testing.yml'
  push:
    branches: main
    paths:
      - 'terraform/apps/**'
      - 'apps/app/src/lambdas/**'
      - 'apps/app/package.json'
      - 'package.json'
      - '.github/**'
      - '!.github/workflows/testing.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  TF_VAR_stage: ${{ github.event_name == 'pull_request' && format('pr{0}', github.event.pull_request.number) || 'prod' }}
  TF_VAR_test_users: ${{ secrets.TEST_USERS }}
  TF_VAR_supabase_url: ${{ secrets.PUBLIC_SUPABASE_URL }}
  TF_VAR_supabase_service_role: ${{ secrets.PRIVATE_SUPABASE_KEY }}
  TF_VAR_notifications_from_address: ${{ secrets.NOTIFICATIONS_FROM_ADDRESS }}
  TF_VAR_supabase_user_profile_table: Settings
  TF_VAR_supabase_reminder_table: Reminder
  TF_VAR_notifications_cron: 0 9 * * ? *
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEPLOYMENT_BUCKET: ${{ secrets.AWS_DEPLOYMENT_BUCKET }}

jobs:
  quality-static:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Check linting
        run: pnpm lint
      - name: Check formatting
        run: pnpm format
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Unit tests
        run: pnpm test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [quality-static, unit-tests]
    defaults:
      run:
        working-directory: ./terraform/apps
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm build:lambdas

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CICD_ROLE_ARN }}
          role-session-name: ${{ secrets.CICD_ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: >
          terraform init
          -backend-config="region=${{ secrets.AWS_REGION }}"
          -backend-config="bucket=${{ secrets.AWS_DEPLOYMENT_BUCKET }}"
          -backend-config="key=${{ secrets.AWS_DEPLOYMENT_BUCKET_FOLDER }}/${{ env.TF_VAR_stage }}"

      - name: Terraform plan
        run: terraform plan
