name: Destroy apps services

on:
  pull_request:
    branches: main
    types: [closed]
    paths:
      - 'terraform/apps/**'
      - 'apps/app/src/lambdas/**'
      - 'apps/app/package.json'
      - 'package.json'
      - '.github/**'
      - '!.github/workflows/testing.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

env:
  TF_VAR_stage: ${{ github.event_name == 'pull_request' && format('pr{0}', github.event.pull_request.number) || 'prod' }}
  TF_VAR_test_users: ${{ secrets.TEST_USERS }}
  TF_VAR_supabase_url: ${{ secrets.PUBLIC_SUPABASE_URL }}
  TF_VAR_supabase_service_role: ${{ secrets.PRIVATE_SUPABASE_KEY }}
  TF_VAR_notifications_from_address: ${{ secrets.NOTIFICATIONS_FROM_ADDRESS }}
  TF_VAR_supabase_user_profile_table: Settings
  TF_VAR_supabase_reminder_table: Reminder
  TF_VAR_notifications_cron: 0 9 * * ? *
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_DEPLOYMENT_BUCKET: ${{ secrets.AWS_DEPLOYMENT_BUCKET }}

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./terraform/apps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build
        run: pnpm build:lambdas
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CICD_ROLE_ARN }}
          role-session-name: ${{ secrets.CICD_ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: >
          terraform init
          -backend-config="region=${{ secrets.AWS_REGION }}"
          -backend-config="bucket=${{ secrets.AWS_DEPLOYMENT_BUCKET }}"
          -backend-config="key=${{ secrets.AWS_DEPLOYMENT_BUCKET_FOLDER }}/${{ env.TF_VAR_stage }}"
      - name: Terraform destroy
        run: terraform destroy -auto-approve
