name: Testing

on:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
  PUBLIC_SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}
  VITE_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_PUBLIC_CLOUDINARY_CLOUD_NAME }}
  PLAYWRIGHT_USERNAME: ${{ secrets.PLAYWRIGHT_USERNAME }}
  PLAYWRIGHT_PASSWORD: ${{ secrets.PLAYWRIGHT_PASSWORD }}
  PUBLIC_ENABLE_MOCKING: true

jobs:
  quality-static:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build apps
        run: pnpm build
      - name: Check types
        run: pnpm types
      - name: Check linting
        run: pnpm lint
      - name: Check formatting
        run: pnpm format
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Unit tests
        run: pnpm test
  accessibility:
    name: Accessibility tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run build
        run: pnpm build
      - name: Run tests
        run: pnpm test:a11y
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results-accessibility
          path: '**/test-results'
          retention-days: 10
  functional:
    name: Functional tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run build
        run: pnpm build
      - name: Run tests
        run: pnpm test:functional
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results-functional
          path: '**/test-results'
          retention-days: 10
  visual:
    name: Visual tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run build
        run: pnpm build
      - name: Run tests
        run: pnpm test:visual
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results-visual
          path: '**/test-results'
          retention-days: 10
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build applications
        run: pnpm build
      - name: Lighthouse tests
        run: pnpm --package=@lhci/cli dlx lhci autorun --config=./apps/marketing/lighthouserc.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
